### ISSUE TITLE
Feature Request: HDR

### ISSUE THREAD

**Issue by reagle** [p00ya/displaymode#11]
I'd like to set HDR mode in addition to resolution and refresh rate.

**Comment by p00ya** [comment]
Hi, thanks for the feature request.

The HDR setting seems to be independent of the CoreGraphics APIs I'm using from displaymode.  I'll do some more research into whether it's possible using other Apple APIs, but an alternative you could use to set HDR programatically is using AppleScript to automate setting it via System Settings, e.g. see:

https://github.com/ppkantorski/macOS-HDR-Toggler/blob/main/HDR%20Toggler.applescript

or possibly via `defaults`... try seeing if anything changes in the output of `defaults read /Library/Preferences/com.apple.windowserver.plist` when you turn HDR on.

**Comment by p00ya** [comment]
I found the right user defaults path and tried the plist approach by setting the BitDepth from 8 to 12:

```
sudo /usr/libexec/PlistBuddy -c "set DisplayAnyUserSets:Configs:0:DisplayConfig:1:LinkDescription:BitDepth 12" /Library/Preferences/com.apple.windowserver.displays.plist
```

but this didn't have any effect (it may do after a restart, though).

In the past, there were appropriate CoreGraphics APIs to identify the pixel depth, but these seem to have been deprecated:

* [CGDisplayModeCopyPixelEncoding](https://developer.apple.com/documentation/coregraphics/1455067-cgdisplaymodecopypixelencoding) was only supported from macOS 10.6 to 10.11
* Poking into the internals of CGDisplayModeRef, in particular to set [kCGDisplayBitsPerPixel](https://developer.apple.com/documentation/coregraphics/kcgdisplaybitsperpixel?language=objc) within its dictionary.
* Dropping down into the IOKit/IOFramebuffer internals to extract the `IODisplayModeInformation`.

So it still looks like the "System Settings" automation is the best way to go for now, since the HDR-ness seems to be intentionally obfuscated in the modern APIs.

**Comment by reagle** [comment]
I'm now using BetterDisplay. https://github.com/waydabber/BetterDisplay/discussions/3624#discussioncomment-11352514
