### ISSUE TITLE
Question: Is it possible to forcedly set Unsupported Resolutions for displays without EDID data ?

### ISSUE THREAD

**Issue by MetaChuh** [p00ya/displaymode#5]
hi @p00ya 

i have an 7.9" retina 1536x2048 mini display with a mipi driver board that does not deliver edid data over hdmi.
link to my specific panel and driver board: [[LQ079L1SX01]](https://www.aliexpress.com/item/4000049907830.html?spm=a2g0o.productlist.0.0.409c7e415RNV81&algo_pvid=31eae220-e084-4d3c-97d6-905322e03aa6&algo_expid=31eae220-e084-4d3c-97d6-905322e03aa6-4&btsid=0b0a555f16231465434208335e1b8e&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_)

so far, while i was able to set the resolution on a raspberry pi manually, i had no luck to set it to 1536x2048 or 2048x1536 on a mac running catalina or big sur.
(the only listed available resolution on macos is 640x480 for this driver board)

do you know a way to forcedly set an unlisted resolution/timing on a mac ?
or is it theoretically possible to set a custom resolution/timing, other than the listed available modes, with displaymode ? 
(on my own risk, of course)

greetings and thanks in advance for any answer. 
@MetaChuh

<br>

ps, if you like this stuff too:
this display panel is for another frankentosh build inside a macintosh classic.
the display should (if i don't mess it up 😬) sit inside the original tube, to make it aesthetically as retro as possible.
if everything works out fine, i'll probably put a mac mini 2012 board inside of it, instead of a raspberry pi 4b.
together with an [[open source adb usb converter]](https://github.com/tmk/tmk_keyboard/tree/master/converter/adb_usb) to use the original keyboard and mouse.

(the tube part will definitively be the hardest, afaik only one i know of, has ever [[built]](https://www.youtube.com/watch?v=3grAxKGzBt0) it [[successfully]](https://www.youtube.com/watch?v=-mMaO6ULuSk), without giving up, or destroying the tube front glass)

**Comment by cburtongit** [comment]
Have you tried turning off and on again?

Kidding, macOS only supports specific resolutions, can’t help you I’m afraid.

On 8 Jun 2021, at 12:04, MetaChuh ***@***.***> wrote:

﻿

hi @p00ya<https://github.com/p00ya>

i have an 7.9" retina 1536x2048 mini display with a mipi driver board that does not deliver edid data over hdmi.
link to my specific panel and driver board: [LQ079L1SX01]<https://www.aliexpress.com/item/4000049907830.html?spm=a2g0o.productlist.0.0.409c7e415RNV81&algo_pvid=31eae220-e084-4d3c-97d6-905322e03aa6&algo_expid=31eae220-e084-4d3c-97d6-905322e03aa6-4&btsid=0b0a555f16231465434208335e1b8e&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_>

so far, while i was able to set the resolution on a raspberry pi manually, i had no luck to set it to 1536x2048 or 2048x1536 on a mac running catalina or big sur.
(the only listed available resolution on macos is 640x480 for this driver board)

do you know a way to forcedly set an unlisted resolution/timing on a mac ?
or is it theoretically possible to set a custom resolution/timing, other than the listed available modes, with displaymode ?
(on my own risk, of course)

greetings and thanks in advance for any answer.
@MetaChuh<https://github.com/MetaChuh>


ps, if you like this stuff too:
this display panel is for another frankentosh build inside a macintosh classic.
the display should (if i don't mess it up 😬) sit inside the original tube, to make it aesthetically as retro as possible.
if everything works out fine, i'll probably put a mac mini 2012 board inside of it, instead of a raspberry pi 4b.
together with an [open source adb usb converter]<https://github.com/tmk/tmk_keyboard/tree/master/converter/adb_usb> to use the original keyboard and mouse.

(the tube part will definitively be the hardest, afaik only one i know of, has ever [built]<https://www.youtube.com/watch?v=3grAxKGzBt0> it [successfully]<https://www.youtube.com/watch?v=-mMaO6ULuSk>, without giving up, or destroying the tube front glass)

**Comment by p00ya** [comment]
Hi @MetaChuh, cool project.

Regarding a way to force an unadvertised resolution from macOS userland, there's no way I know of unfortunately, and certainly not with the APIs displaymode is using.  There are also some undocumented CoreGraphics APIs that might let you force something, but I doubt even that will work.

However, I expect it would be possible if you wrote a kernel extension that faked the EDID.

A hardware solution (a microcontroller on the I2C bus between the driver board and the mac, providing the appropriate EDID) could also work.

**Comment by MetaChuh** [comment]
hi @p00ya ,
thanks for the reply and the ideas 👍

good idea, i'll most probably build an edid inserter with a working edid dump using an 24LC22A on the i2c lines of the hdmi.
seems to be the quickest, most flexible and platform independent solution for now 👍

i'm closing this issue as answered.

greetings and best regards,
@MetaChuh

**Comment by p00ya** [comment]
For the historical record, if you can set at least a vendor and product ID via the hardware EDID injector, then you can override the remaining EDID data macOS uses from userland via a plist in the file `/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-$VENDORID/DisplayProductID-$PRODUCTID`.  The plist has a base64-encoded EDID payload under the `IODisplayEDID` key.  For an example of crafting the plist, see https://gist.github.com/adaugherity/7435890
